import cat1 from '../img/cat1.webp';
import findCat from '../img/findCat.png'
import CatInGarden from '../img/CatInGarden.jpg';
import lostCat from '../img/lostCat.png';
import lostDog from '../img/lostDog.png';
import Dog from '../img/Dog.webp';
import gingeCat from '../img/findCat.png'
import horse from '../img/horse.jpg';
import helpMe from '../img/HelpMe.jpg';
import LetsGo from '../img/LetsGo.jpg';
import Improving from '../img/Improving.jpg';



export const PETS = [
    {
        id: 0,
        name: 'cat1',
        image: cat1,
        description:
            'cat'
    },
    {
        id: 1,
        name: 'findCat',
        image: findCat,
        description:
            'findCat'
    },
    {
        id: 2,
        name: 'Dog',
        image: Dog,
        description:
            'dog'
    }, 
    {
        id: 3,
        name: 'gingeCat',
        image: gingeCat,
        description:
            'gingeCat'
    },
    {
        id: 4,
        name: 'horse',
        image: horse,
        description:
            'horse'
    },
    {
        id: 5,
        name: 'helpMe',
        image: helpMe,
        description:
            'helpMe'
    },
    {
        id: 7,
        name: 'LetsGo',
        image: LetsGo,
        description:
            'LetsGo'
    }, 
    {
        id: 8,
        name: 'Improving',
        image: Improving,
        description:
            'Improving'
    }
]